version: "3"
services:
  httpd:
    container_name: httpd
    image: httpd:latest
    ports:
      - 5004:80
    volumes:
      - /opt/data:/usr/local/apache2/htdocs
  



---
version: "3"
services:
  web:
    container_name: php_apache
    image: php:5.6-apache
    ports:
      - 8083:80
    volumes:
      - /var/www/html:/var/www/html
  db:
    container_name: mysql_apache
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'database_apache'
      MARIADB_ROOT_PASSWORD: 'Admin=Reddy'

    